development:
  adapter: postgresql
  encoding: unicode
  database: spg_map_viz_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: spg_map_viz_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: spg_map_viz_production
  pool: 5
  timeout: 5000
